---
- name: "PLAY 1: WORKING WITH IOS USER MODULE"
  hosts: cisco_routers
  connection: network_cli
  tasks:
    - name: "TASK 1: Add local username with SSH Key"
      ios_user:
        name: josh2
        configured_password: "{{ lookup('env', 'NEW_PASSWORD') }}"
        state: present
        privilege: 15
      register: config_output

    - debug:
        msg: "{{ config_output }}"

    - name: "FINAL TASK: Save Config"
      ios_config:
        save_when: always
